### ISSUE TITLE
Run 'vnx-benchmark-throughput' with no results output on U50

### ISSUE THREAD

**Issue by IskandarZhang** [Xilinx/xup_vitis_network_example#44]
After debugging, I suggest there are two main errors but I have no idea about how to solve them. My lightly modified code and output info were attached below:
### Codes:
xclbin = 
'/home/username/xup_vitis_network_example/benchmark.intf0.xilinx_u50_gen3x16_xdma_201920_3/vnx_benchmark_if0.xclbin'
ol_w0 = pynq.Overlay(xclbin, device=pynq.Device.devices[1])
ol_w1 = pynq.Overlay(xclbin, device=pynq.Device.devices[2])

print("Link worker 0 {}; link worker 1 {}".format(ol_w0.cmac_0.linkStatus(),ol_w1.cmac_0.linkStatus()))

print(ol_w1.networklayer_0.updateIPAddress('172.17.1.133', debug=True, gwaddr='172.17.1.94'))
print(ol_w0.networklayer_0.updateIPAddress('172.17.1.166', debug=True, gwaddr='172.17.1.94'))
print(ol_w1.networklayer_0.getNetworkInfo())

ol_w1.networklayer_0.sockets[0] = ('172.17.1.166', 39187, 41845, True)
ol_w1.networklayer_0.populateSocketTable()

ol_w1.networklayer_0.arpDiscovery()

print(ol_w1.networklayer_0.readARPTable())

ol_w0.networklayer_0.sockets[7] = ('172.17.1.133', 41845, 39187, True)
ol_w0.networklayer_0.populateSocketTable()

ol_w0.networklayer_0.arpDiscovery()

print(ol_w0.networklayer_0.readARPTable())

ol_w1_tg = ol_w1.traffic_generator_0_0
ol_w1_tg.register_map.mode = benchmark_mode.index('LOOPBACK')
ol_w1_tg.register_map.dest_id = 0 # Use connection in position 0 to reflect
ol_w1_tg.register_map.CTRL.AP_START = 1

import time
freq = int(ol_w1.clock_dict['clock0']['frequency'])
ol_w0_tg = ol_w0.traffic_generator_0_3
experiment_dict = {}
local_dict = {}
ol_w0_tg.register_map.mode = benchmark_mode.index('PRODUCER')
ol_w0_tg.register_map.dest_id = 7
ol_w1_tg.freq = freq
ol_w0_tg.freq = freq
for pkt in [1_000_000, 1_000_000_000]:
    ol_w0_tg.register_map.debug_reset = 1
    ol_w1_tg.register_map.debug_reset = 1
    ol_w0_tg.register_map.time_between_packets = 0
    ol_w0_tg.register_map.number_packets = pkt
    local_dict = {}
    for i in range(23):
        beats = i + 1
        ol_w0_tg.register_map.number_beats = beats
        ol_w0_tg.register_map.CTRL.AP_START = 1
        while int(ol_w0_tg.register_map.out_traffic_packets) != pkt:
            time.sleep(0.8)
        # Get results from local and remote worker
        rx_tot_pkt, rx_thr, rx_time = ol_w1_tg.computeThroughputApp('rx')
        tx_tot_pkt, tx_thr, tx_time = ol_w0_tg.computeThroughputApp('tx')
        #Create dict entry for this particular experiment
        entry_dict = {'size': (beats * 64), 'rx_pkts' : rx_tot_pkt, 'tx_thr': tx_thr, 'rx_thr': rx_thr}
        local_dict[beats] = entry_dict
        # Reset probes to prepare for next computation
        ol_w0_tg.resetProbes()
        ol_w1_tg.resetProbes() 
        #Compute theoretical maximum at application level, overhead is UDP (8), IP (20), Ethernet(14) and FCS (4)
        theoretical = (beats * 64 * 100)/((beats*64)+8+20+14+4) 
        print("Sent {:14,} size: {:4}-Byte done!\tGot {:14,} took {:8.4f} sec, thr: {:.3f} Gbps, theoretical {:.3f}, difference {:.3f}"\
              .format(pkt,beats*64, rx_tot_pkt, rx_time, rx_thr, theoretical, theoretical-rx_thr))
        time.sleep(0.5)
    experiment_dict[pkt] = local_dict

### Info:
/home/username/xup_vitis_network_example/Notebooks/vnx_utils.py:499: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if gwaddr is "None":
/home/username/xup_vitis_network_example/Notebooks/vnx_utils.py:630: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if direction is "rx":
Link worker 0 {'cmac_link': True}; link worker 1 {'cmac_link': True}
{'HWaddr': '00:0a:35:02:9d:7b', 'inet addr': '172.17.1.133', 'gateway addr': '172.17.1.94', 'Mask': '255.255.255.0'}
{'HWaddr': '00:0a:35:02:9d:9c', 'inet addr': '172.17.1.166', 'gateway addr': '172.17.1.94', 'Mask': '255.255.255.0'}
{'HWaddr': '00:0a:35:02:9d:7b', 'inet addr': '172.17.1.133', 'gateway addr': '172.17.1.94', 'Mask': '255.255.255.0'}
{156: {'MAC address': '00:0a:35:02:9d:9c', 'IP address': '172.17.1.156'}}
{123: {'MAC address': '00:0a:35:02:9d:7b', 'IP address': '172.17.1.123'}}

### Suggestions:
As the info shows, although I changed the IP adress of two U50 but the print result suggests that it didn't change for some reason. And the whole program was stuck at `        while int(ol_w0_tg.register_map.out_traffic_packets) != pkt:
            time.sleep(0.8)` So I consider that the receiver didn't get any packets at all but I still have no idea about the reasons.
Looking forward to your reply eagerly.

**Comment by mariodruiz** [comment]
Hi,

Your code is very hard to read, please use code snippets https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks 

It seems that you have at least 3 Alveo cards in your system. How are they connected to the network?

Did you try reseting the cards before rerunning?

Information about PYNQ and XRT will be helpful

**Comment by IskandarZhang** [comment]
> Hi,
> 
> Your code is very hard to read, please use code snippets https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
> 
> It seems that you have at least 3 Alveo cards in your system. How are they connected to the network?
> 
> Did you try reseting the cards before rerunning?
> 
> Information about PYNQ and XRT will be helpful

Hi Mario, I'm a starter on Github and very sorry to list such hard-reading codes. Hope the code block helps.
```Python
xclbin =
'/home/username/xup_vitis_network_example/benchmark.intf0.xilinx_u50_gen3x16_xdma_201920_3/vnx_benchmark_if0.xclbin'
ol_w0 = pynq.Overlay(xclbin, device=pynq.Device.devices[1])
ol_w1 = pynq.Overlay(xclbin, device=pynq.Device.devices[2])

print("Link worker 0 {}; link worker 1 {}".format(ol_w0.cmac_0.linkStatus(),ol_w1.cmac_0.linkStatus()))

print(ol_w1.networklayer_0.updateIPAddress('172.17.1.133', debug=True, gwaddr='172.17.1.94'))
print(ol_w0.networklayer_0.updateIPAddress('172.17.1.166', debug=True, gwaddr='172.17.1.94'))
print(ol_w1.networklayer_0.getNetworkInfo())

ol_w1.networklayer_0.sockets[0] = ('172.17.1.166', 39187, 41845, True)
ol_w1.networklayer_0.populateSocketTable()

ol_w1.networklayer_0.arpDiscovery()

print(ol_w1.networklayer_0.readARPTable())

ol_w0.networklayer_0.sockets[7] = ('172.17.1.133', 41845, 39187, True)
ol_w0.networklayer_0.populateSocketTable()

ol_w0.networklayer_0.arpDiscovery()

print(ol_w0.networklayer_0.readARPTable())

ol_w1_tg = ol_w1.traffic_generator_0_0
ol_w1_tg.register_map.mode = benchmark_mode.index('LOOPBACK')
ol_w1_tg.register_map.dest_id = 0 # Use connection in position 0 to reflect
ol_w1_tg.register_map.CTRL.AP_START = 1

import time
freq = int(ol_w1.clock_dict['clock0']['frequency'])
ol_w0_tg = ol_w0.traffic_generator_0_3
experiment_dict = {}
local_dict = {}
ol_w0_tg.register_map.mode = benchmark_mode.index('PRODUCER')
ol_w0_tg.register_map.dest_id = 7
ol_w1_tg.freq = freq
ol_w0_tg.freq = freq
for pkt in [1_000_000, 1_000_000_000]:
ol_w0_tg.register_map.debug_reset = 1
ol_w1_tg.register_map.debug_reset = 1
ol_w0_tg.register_map.time_between_packets = 0
ol_w0_tg.register_map.number_packets = pkt
local_dict = {}
for i in range(23):
beats = i + 1
ol_w0_tg.register_map.number_beats = beats
ol_w0_tg.register_map.CTRL.AP_START = 1
while int(ol_w0_tg.register_map.out_traffic_packets) != pkt:
time.sleep(0.8)
# Get results from local and remote worker
rx_tot_pkt, rx_thr, rx_time = ol_w1_tg.computeThroughputApp('rx')
tx_tot_pkt, tx_thr, tx_time = ol_w0_tg.computeThroughputApp('tx')
#Create dict entry for this particular experiment
entry_dict = {'size': (beats * 64), 'rx_pkts' : rx_tot_pkt, 'tx_thr': tx_thr, 'rx_thr': rx_thr}
local_dict[beats] = entry_dict
# Reset probes to prepare for next computation
ol_w0_tg.resetProbes()
ol_w1_tg.resetProbes()
#Compute theoretical maximum at application level, overhead is UDP (8), IP (20), Ethernet(14) and FCS (4)
theoretical = (beats * 64 * 100)/((beats64)+8+20+14+4)
print("Sent {:14,} size: {:4}-Byte done!\tGot {:14,} took {:8.4f} sec, thr: {:.3f} Gbps, theoretical {:.3f}, difference {:.3f}"
.format(pkt,beats64, rx_tot_pkt, rx_time, rx_thr, theoretical, theoretical-rx_thr))
time.sleep(0.5)
experiment_dict[pkt] = local_dict
```
There are three Alveo U50 on my server actually, but one of them act as a normal NIC and I never download .xclbin file to it. Only two of them was linked in the network by using dask distribution.

I once reset them before running, but it didn't help.

Output of `xbutil examine` command is attached below:

```
System Configuration
  OS Name              : Linux
  Release              : 5.4.0-89-generic
  Version              : #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021
  Machine              : x86_64
  CPU Cores            : 32
  Memory               : 257536 MB
  Distribution         : Ubuntu 20.04.3 LTS
  GLIBC                : 2.31
  Model                : 2288H V5

XRT
  Version              : 2.11.634
  Branch               : 2021.1
  Hash                 : 5ad5998d67080f00bca5bf15b3838cf35e0a7b26
  Hash Date            : 2021-06-08 22:08:45
  XOCL                 : 2.11.634, 5ad5998d67080f00bca5bf15b3838cf35e0a7b26
  XCLMGMT              : 2.11.634, 5ad5998d67080f00bca5bf15b3838cf35e0a7b26

Devices present
  [0000:87:00.1] : xilinx_u50_gen3x16_xdma_201920_3
  [0000:5e:00.1] : xilinx_u50_gen3x16_xdma_201920_3
  [0000:3c:00.1] : xilinx_u50_gen3x16_xdma_201920_3

```
and the PYNQ version is 2.6.2.
Best.

**Comment by mariodruiz** [comment]
How are the two U50 that you are using for the experiment connected? Point to point or via switch? 

After you stop the cell. What is the output of  `ol_w1_tg.getDebugProbes()` and `ol_w0_tg.getDebugProbes()`

Is there any reason why the `ol_w1_tg` is configured as LOOPBACK? I have not verified this combination.

**Comment by IskandarZhang** [comment]
> How are the two U50 that you are using for the experiment connected? Point to point or via switch?
> 
> After you stop the cell. What is the output of `ol_w1_tg.getDebugProbes()` and `ol_w0_tg.getDebugProbes()`
> 
> Is there any reason why the `ol_w1_tg` is configured as LOOPBACK? I have not verified this combination.

Hi Mario, sorry for so late reply. It's point to point, but I copied all the codes of cell to a new .py file then run it instead of running in the cells, which aims to bypass a kernel that I thought might cause problem at the time.  

I found that `getDebugProbes` was defined in class `Networklayer` but not in `TrafficGenerator` .So when I code `print(ol_w1_tg.getDebugProbes())` it raised error:
`AttributeError
'TrafficGenerator' object has no attribute 'getDebugProbes'` . I have to code `print(ol_w0.networklayer_0.getDebugProbes)` and `print(ol_w1.networklayer_0.getDebugProbes)` to instead and the output is attached below:
```
{'tx_path': {'arp': {'packets': 1532, 'bytes': 91920, 'cycles': 1178146855234}, 'icmp': {'packets': 0, 'bytes': 0, 'cycles': 0}, 'ethernet_header_inserter': {'packets': 1000000, 'bytes': 106000000, 'cycles': 3551002}, 'ethernet': {'packets': 1001532, 'bytes': 106091920, 'cycles': 1178146855234}, 'udp_from_app': {'packets': 1000000, 'bytes': 64000000, 'cycles': 3550070}, 'udp': {'packets': 1000000, 'bytes': 92000000, 'cycles': 3550979}}, 'rx_path': {'ethernet': {'packets': 356, 'bytes': 27760, 'cycles': 16404889}, 'packet_handler': {'packets': 346, 'bytes': 25210, 'cycles': 16404884}, 'arp': {'packets': 257, 'bytes': 15420, 'cycles': 4039023}, 'icmp': {'packets': 0, 'bytes': 0, 'cycles': 0}, 'udp': {'packets': 89, 'bytes': 9790, 'cycles': 349}, 'udp_to_app': {'packets': 89, 'bytes': 7298, 'cycles': 358}}}
{'tx_path': {'arp': {'packets': 1532, 'bytes': 91920, 'cycles': 1178141525931}, 'icmp': {'packets': 0, 'bytes': 0, 'cycles': 0}, 'ethernet_header_inserter': {'packets': 1000000, 'bytes': 124000000, 'cycles': 3551994}, 'ethernet': {'packets': 1001532, 'bytes': 124091920, 'cycles': 1178141525931}, 'udp_from_app': {'packets': 1000000, 'bytes': 82000000, 'cycles': 3551994}, 'udp': {'packets': 1000000, 'bytes': 110000000, 'cycles': 3551994}}, 'rx_path': {'ethernet': {'packets': 1001532, 'bytes': 124091920, 'cycles': 1178146582325}, 'packet_handler': {'packets': 1001532, 'bytes': 110091920, 'cycles': 1178146582325}, 'arp': {'packets': 1532, 'bytes': 91920, 'cycles': 1178146582325}, 'icmp': {'packets': 0, 'bytes': 0, 'cycles': 0}, 'udp': {'packets': 1000000, 'bytes': 110000000, 'cycles': 3551994}, 'udp_to_app': {'packets': 1000000, 'bytes': 82000000, 'cycles': 3551994}}}
``` 

In order to troubleshoot whether the board is faulty and cannot send or receive packets, I interchanged the functions of `ol_w1_tg` and `ol_w0_tg`, but there is not any more special purpose other than that. The result shows that both boards can be used as packets sender, but neither can receive the packet sent by the other also.

**Comment by mariodruiz** [comment]
Can you please provide Vitis and XRT version?
Also, what commit did you build against?

Did you try to run the notebook as-is? Removing the dask part as described here https://github.com/Xilinx/xup_vitis_network_example/tree/master/Notebooks#multiple-alveo-cards-in-the-same-system

**Comment by IskandarZhang** [comment]
> > Can you please provide Vitis and XRT version? Also, what commit did you build against?
> > Did you try to run the notebook as-is? Removing the dask part as described here https://github.com/Xilinx/xup_vitis_network_example/tree/master/Notebooks#multiple-alveo-cards-in-the-same-system
> 
> My XRT version is 2.11.634 and Vitis version is 2021.1. I'm sorry that I'm not very sure about what's your meaning, I built .xclbin file via `make all...` command as Readme guided. I did try to run it as-is, I mean run the cells one by one and tried to remove dask part as below:
> 
> ```python
> xclbin = '/home/username/xup_vitis_network_example/benchmark.intf0.xilinx_u50_gen3x16_xdma_201920_3/vnx_benchmark_if0.xclbin'
> ol_w0 = pynq.Overlay(xclbin, device=pynq.Device.devices[1])
> ol_w1 = pynq.Overlay(xclbin, device=pynq.Device.devices[2])
> ```
> 
> Then it was also stuck in this cell:
> 
> ```python
> import time
> freq = int(ol_w1.clock_dict['clock0']['frequency'])
> ol_w0_tg = ol_w0.traffic_generator_0_3
> experiment_dict = {}
> local_dict = {}
> ol_w0_tg.register_map.mode = benchmark_mode.index('PRODUCER')
> ol_w0_tg.register_map.dest_id = 7
> ol_w1_tg.freq = freq
> ol_w0_tg.freq = freq
> for pkt in [1_000_000, 1_000_000_000]:
>     ol_w0_tg.register_map.debug_reset = 1
>     ol_w1_tg.register_map.debug_reset = 1
>     ol_w0_tg.register_map.time_between_packets = 0
>     ol_w0_tg.register_map.number_packets = pkt
>     local_dict = {}
>     for i in range(23):
>         beats = i + 1
>         ol_w0_tg.register_map.number_beats = beats
>         ol_w0_tg.register_map.CTRL.AP_START = 1
>         while int(ol_w0_tg.register_map.out_traffic_packets) != pkt:
>             time.sleep(0.8)
>         # Get results from local and remote worker
>         rx_tot_pkt, rx_thr, rx_time = ol_w1_tg.computeThroughputApp('rx')
>         tx_tot_pkt, tx_thr, tx_time = ol_w0_tg.computeThroughputApp('tx')
>         #Create dict entry for this particular experiment
>         entry_dict = {'size': (beats * 64), 'rx_pkts' : rx_tot_pkt, 'tx_thr': tx_thr, 'rx_thr': rx_thr}
>         local_dict[beats] = entry_dict
>         # Reset probes to prepare for next computation
>         ol_w0_tg.resetProbes()
>         ol_w1_tg.resetProbes() 
>         #Compute theoretical maximum at application level, overhead is UDP (8), IP (20), Ethernet(14) and FCS (4)
>         theoretical = (beats * 64 * 100)/((beats*64)+8+20+14+4) 
>         print("Sent {:14,} size: {:4}-Byte done!\tGot {:14,} took {:8.4f} sec, thr: {:.3f} Gbps, theoretical {:.3f}, difference {:.3f}"\
>               .format(pkt,beats*64, rx_tot_pkt, rx_time, rx_thr, theoretical, theoretical-rx_thr))
>         time.sleep(0.5)
>     experiment_dict[pkt] = local_dict
> ```
> 
> This stuck manifests itself as a fruitless running for up to half an hour even longer. After my inspection, it stuck in codes:
> 
> ```python
>         while int(ol_w0_tg.register_map.out_traffic_packets) != pkt:
>             time.sleep(0.8)
> ```
> 
> I suggest it never jumped out of `while` but I cannot figure out the reason. Best.

```Python
KeyboardInterrupt                         Traceback (most recent call last)
/tmp/ipykernel_1989188/2286208883.py in <module>
     19         ol_w0_tg.register_map.CTRL.AP_START = 1
     20         while int(ol_w0_tg.register_map.out_traffic_packets) != pkt:
---> 21             time.sleep(0.8)
     22         # Get results from local and remote worker
     23         rx_tot_pkt, rx_thr, rx_time = ol_w1_tg.computeThroughputApp('rx')

KeyboardInterrupt: 
```
as the info shows above

**Comment by mariodruiz** [comment]
To get your current commit hash run this within the folder where you ran make.

```sh
git log -1 --pretty=format:"%H"
```

**Comment by IskandarZhang** [comment]
> To get your current commit hash run this within the folder where you ran make.
> 
> ```shell
> git log -1 --pretty=format:"%H"
> ```

Thanks for your guide. And the output is:
`e07b6463259ecd0388d8e3b4753860c1da19fd78`

**Comment by mariodruiz** [comment]
An issue was solved in a newer commit. https://github.com/Xilinx/xup_vitis_network_example/commit/4200ca563f67aa95db52aed1d6d9c5c2ddaeca62

- Can you please pull the latest changes?
- Run `make distclean` in the `Ethernet` folder
- Run `make distclean` in the root folder
- Rebuild the design and try again. 

Alternatively, you can clone the repository again.

**Comment by IskandarZhang** [comment]
> An issue was solved in a newer commit. [4200ca5](https://github.com/Xilinx/xup_vitis_network_example/commit/4200ca563f67aa95db52aed1d6d9c5c2ddaeca62)
> 
> * Can you please pull the latest changes?
> * Run `make distclean` in the `Ethernet` folder
> * Run `make distclean` in the root folder
> * Rebuild the design and try again.
> 
> Alternatively, you can clone the repository again.

Thanks for your advise, but when I clone the repository again and type command
` make all TARGET=/opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_201920_3/xilinx_u50_gen3x16_xdma_201920_3.xpfm INTERFACE=0 DESIGN=benchmark` some errors occured:
```
cp config_files/connectivity_benchmark_if0.ini configuration_benchmark_if0.tmp.ini
echo "" >> configuration_benchmark_if0.tmp.ini
echo "" >> configuration_benchmark_if0.tmp.ini
echo "[advanced]" >> configuration_benchmark_if0.tmp.ini
echo "param=compiler.userPostSysLinkOverlayTcl=/home/username/xup_vitis_network_example-master/Ethernet/post_sys_link.tcl" >> configuration_benchmark_if0.tmp.ini
#echo "param=compiler.worstNegativeSlack=-2" >> configuration_benchmark_if0.tmp.ini
#echo "param=compiler.compiler.errorOnHoldViolation=false" >> configuration_benchmark_if0.tmp.ini
make -C NetLayers/ all DEVICE=xilinx_u50_gen3x16_xdma_201920_3
make[1]: Entering directory '/home/username/xup_vitis_network_example-master/NetLayers'
mkdir -p ./_x.xilinx_u50_gen3x16_xdma_201920_3
make -C 100G-fpga-network-stack-core hbm
make[2]: Entering directory '/home/username/xup_vitis_network_example-master/NetLayers/100G-fpga-network-stack-core'
make[2]: *** No rule to make target 'hbm'.  Stop.
make[2]: Leaving directory '/home/username/xup_vitis_network_example-master/NetLayers/100G-fpga-network-stack-core'
make[1]: *** [Makefile:65: _x.xilinx_u50_gen3x16_xdma_201920_3/networklayer.xo] Error 2
make[1]: Leaving directory '/home/username/xup_vitis_network_example-master/NetLayers'
make: *** [Makefile:122: NetLayers/_x.xilinx_u50_gen3x16_xdma_201920_3/networklayer.xo] Error 2
```
may I ask for further advise about how to fix it?
Best.

**Comment by mariodruiz** [comment]
It seems that you did not clone the repository recursively. To get the submodules run

```sh
git submodule init
git submodule update
```

Then run `make` again

**Comment by IskandarZhang** [comment]
> It seems that you did not clone the repository recursively. To get the submodules run
> 
> ```shell
> git submodule init
> git submodule update
> ```
> 
> Then run `make` again

I cloned the repository and generated `vnx_benchmark_if0.xclbin`, then I remove dask as the [guide](https://github.com/Xilinx/xup_vitis_network_example/tree/master/Notebooks#multiple-alveo-cards-in-the-same-system) said but the error still occurs when I run the cell:
```Python
import time
freq = int(ol_w1.clock_dict['clock0']['frequency'])
ol_w0_tg = ol_w0.traffic_generator_0_3
experiment_dict = {}
local_dict = {}
ol_w0_tg.register_map.mode = benchmark_mode.index('PRODUCER')
ol_w0_tg.register_map.dest_id = 7
ol_w1_tg.freq = freq
ol_w0_tg.freq = freq
for pkt in [1_000_000, 1_000_000_000]:
    ol_w0_tg.register_map.debug_reset = 1
    ol_w1_tg.register_map.debug_reset = 1
    ol_w0_tg.register_map.time_between_packets = 0
    ol_w0_tg.register_map.number_packets = pkt
    local_dict = {}
    for i in range(23):
        beats = i + 1
        ol_w0_tg.register_map.number_beats = beats
        ol_w0_tg.register_map.CTRL.AP_START = 1
        while int(ol_w0_tg.register_map.out_traffic_packets) != pkt:
            time.sleep(0.8)
        # Get results from local and remote worker
        rx_tot_pkt, rx_thr, rx_time = ol_w1_tg.computeThroughputApp('rx')
        tx_tot_pkt, tx_thr, tx_time = ol_w0_tg.computeThroughputApp('tx')
        #Create dict entry for this particular experiment
        entry_dict = {'size': (beats * 64), 'rx_pkts' : rx_tot_pkt, 'tx_thr': tx_thr, 'rx_thr': rx_thr}
        local_dict[beats] = entry_dict
        # Reset probes to prepare for next computation
        ol_w0_tg.resetProbes()
        ol_w1_tg.resetProbes() 
        #Compute theoretical maximum at application level, overhead is UDP (8), IP (20), Ethernet(14) and FCS (4)
        theoretical = (beats * 64 * 100)/((beats*64)+8+20+14+4) 
        print("Sent {:14,} size: {:4}-Byte done!\tGot {:14,} took {:8.4f} sec, thr: {:.3f} Gbps, theoretical {:.3f}, difference {:.3f}"\
              .format(pkt,beats*64, rx_tot_pkt, rx_time, rx_thr, theoretical, theoretical-rx_thr))
        time.sleep(0.5)
    experiment_dict[pkt] = local_dict
```
```
ZeroDivisionError                         Traceback (most recent call last)
/tmp/ipykernel_3405816/2286208883.py in <module>
     21             time.sleep(0.8)
     22         # Get results from local and remote worker
---> 23         rx_tot_pkt, rx_thr, rx_time = ol_w1_tg.computeThroughputApp('rx')
     24         tx_tot_pkt, tx_thr, tx_time = ol_w0_tg.computeThroughputApp('tx')
     25         #Create dict entry for this particular experiment

~/xup_vitis_network_example-master/Notebooks/vnx_utils.py in computeThroughputApp(self, direction)
    638 
    639         tot_time = (1 / (self.freq * 10 ** 6)) * tot_cycles
--> 640         thr_bs = ((tot_bytes * 8) + 1)/ (tot_time +1)
    641 
    642         return tot_pkts, thr_bs / (10 ** 9), tot_time

ZeroDivisionError: float division by zero
```
have you ever came up with any similar errors?
Best.

**Comment by mariodruiz** [comment]
That rules out the hardware.

Can you please try to reverse the range in the for loop. 

```python
    ....
    local_dict = {}
    for i in reversed(range(23)):
        beats = i + 1
       ....
```

In the past someone had a similar issue, and reversing the loop solved the problem. Hopefully, it will do the same here

**Comment by IskandarZhang** [comment]
> That rules out the hardware.
> 
> Can you please try to reverse the range in the for loop.
> 
> ```python
>     ....
>     local_dict = {}
>     for i in reversed(range(23)):
>         beats = i + 1
>        ....
> ```
> 
> In the past someone had a similar issue, and reversing the loop solved the problem. Hopefully, it will do the same here

Hi Mario, the zero division error is solved but I don't think it is solved forever, or say thoroughly as the zero division error still occurs sometime. What's worse, there are still no any received packets, which behave as:
```
Sent      1,000,000 size: 1472-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 96.970, difference 96.970
Sent      1,000,000 size: 1408-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 96.836, difference 96.836
Sent      1,000,000 size: 1344-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 96.691, difference 96.691
Sent      1,000,000 size: 1280-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 96.531, difference 96.531
Sent      1,000,000 size: 1216-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 96.355, difference 96.355
Sent      1,000,000 size: 1152-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 96.160, difference 96.160
Sent      1,000,000 size: 1088-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 95.944, difference 95.944
Sent      1,000,000 size: 1024-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 95.701, difference 95.701
Sent      1,000,000 size:  960-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 95.427, difference 95.427
Sent      1,000,000 size:  896-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 95.117, difference 95.117
Sent      1,000,000 size:  832-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 94.761, difference 94.761
Sent      1,000,000 size:  768-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 94.349, difference 94.349
Sent      1,000,000 size:  704-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 93.867, difference 93.867
Sent      1,000,000 size:  640-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 93.294, difference 93.294
Sent      1,000,000 size:  576-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 92.605, difference 92.605
Sent      1,000,000 size:  512-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 91.756, difference 91.756
Sent      1,000,000 size:  448-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 90.688, difference 90.688
Sent      1,000,000 size:  384-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 89.302, difference 89.302
Sent      1,000,000 size:  320-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 87.432, difference 87.432
Sent      1,000,000 size:  256-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 84.768, difference 84.768
Sent      1,000,000 size:  192-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 80.672, difference 80.672
Sent      1,000,000 size:  128-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 73.563, difference 73.563
Sent      1,000,000 size:   64-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 58.182, difference 58.182
Sent  1,000,000,000 size: 1472-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 96.970, difference 96.970
Sent  1,000,000,000 size: 1408-Byte done!	Got              0 took   0.0000 sec, thr: 0.000 Gbps, theoretical 96.836, difference 
```
That's just a part of output but I do thinks it can indicate some problems.
What's more, I recalled that there was a time when I successfully ran the program, but it only output partial results and got stuck. So I'm really not sure if we can rule out the hardware. 
Best.

**Comment by IskandarZhang** [comment]
> That rules out the hardware.
> 
> Can you please try to reverse the range in the for loop.
> 
> ```python
>     ....
>     local_dict = {}
>     for i in reversed(range(23)):
>         beats = i + 1
>        ....
> ```
> 
> In the past someone had a similar issue, and reversing the loop solved the problem. Hopefully, it will do the same here

Hi Mario, after I re-installed `pynq` , the cell can partially run normally, although this is also an unstable situation.  The reason I say this is that it sometimes still has `ZeroDivisionError`, and the result is also problematic if it can run. It is mainly reflected in the fact that the actual A Million Packets throughput is very low, and the results are attached: 
```
Sent      1,000,000 size:   64-Byte done!	Got      1,000,000 took   0.0104 sec, thr: 0.507 Gbps, theoretical 58.182, difference 57.675
Sent      1,000,000 size:  128-Byte done!	Got      1,000,000 took   0.0167 sec, thr: 1.007 Gbps, theoretical 73.563, difference 72.556
Sent      1,000,000 size:  192-Byte done!	Got      1,000,000 took   0.0206 sec, thr: 1.505 Gbps, theoretical 80.672, difference 79.167
Sent      1,000,000 size:  256-Byte done!	Got      1,000,000 took   0.0258 sec, thr: 1.997 Gbps, theoretical 84.768, difference 82.772
Sent      1,000,000 size:  320-Byte done!	Got      1,000,000 took   0.0309 sec, thr: 2.483 Gbps, theoretical 87.432, difference 84.948
Sent      1,000,000 size:  384-Byte done!	Got      1,000,000 took   0.0360 sec, thr: 2.965 Gbps, theoretical 89.302, difference 86.337
Sent      1,000,000 size:  448-Byte done!	Got      1,000,000 took   0.0411 sec, thr: 3.442 Gbps, theoretical 90.688, difference 87.246
Sent      1,000,000 size:  512-Byte done!	Got      1,000,000 took   0.0462 sec, thr: 3.915 Gbps, theoretical 91.756, difference 87.841
Sent      1,000,000 size:  576-Byte done!	Got      1,000,000 took   0.0514 sec, thr: 4.383 Gbps, theoretical 92.605, difference 88.222
Sent      1,000,000 size:  640-Byte done!	Got      1,000,000 took   0.0565 sec, thr: 4.846 Gbps, theoretical 93.294, difference 88.448
Sent      1,000,000 size:  704-Byte done!	Got      1,000,000 took   0.0616 sec, thr: 5.305 Gbps, theoretical 93.867, difference 88.561
Sent      1,000,000 size:  768-Byte done!	Got      1,000,000 took   0.0667 sec, thr: 5.760 Gbps, theoretical 94.349, difference 88.589
Sent      1,000,000 size:  832-Byte done!	Got      1,000,000 took   0.0718 sec, thr: 6.210 Gbps, theoretical 94.761, difference 88.551
Sent      1,000,000 size:  896-Byte done!	Got      1,000,000 took   0.0770 sec, thr: 6.656 Gbps, theoretical 95.117, difference 88.461
Sent      1,000,000 size:  960-Byte done!	Got      1,000,000 took   0.0821 sec, thr: 7.097 Gbps, theoretical 95.427, difference 88.330
Sent      1,000,000 size: 1024-Byte done!	Got      1,000,000 took   0.0872 sec, thr: 7.535 Gbps, theoretical 95.701, difference 88.166
Sent      1,000,000 size: 1088-Byte done!	Got      1,000,000 took   0.0923 sec, thr: 7.968 Gbps, theoretical 95.944, difference 87.975
Sent      1,000,000 size: 1152-Byte done!	Got      1,000,000 took   0.0974 sec, thr: 8.398 Gbps, theoretical 96.160, difference 87.763
Sent      1,000,000 size: 1216-Byte done!	Got      1,000,000 took   0.1026 sec, thr: 8.823 Gbps, theoretical 96.355, difference 87.532
Sent      1,000,000 size: 1280-Byte done!	Got      1,000,000 took   0.1077 sec, thr: 9.245 Gbps, theoretical 96.531, difference 87.286
Sent      1,000,000 size: 1344-Byte done!	Got      1,000,000 took   0.1128 sec, thr: 9.662 Gbps, theoretical 96.691, difference 87.029
Sent      1,000,000 size: 1408-Byte done!	Got      1,000,000 took   0.1179 sec, thr: 10.076 Gbps, theoretical 96.836, difference 86.760
Sent      1,000,000 size: 1472-Byte done!	Got      1,000,000 took   0.1230 sec, thr: 10.486 Gbps, theoretical 96.970, difference 86.484
Sent  1,000,000,000 size:   64-Byte done!	Got  1,000,000,000 took  10.4000 sec, thr: 44.912 Gbps, theoretical 58.182, difference 13.270
Sent  1,000,000,000 size:  128-Byte done!	Got  1,000,000,000 took  16.6667 sec, thr: 57.962 Gbps, theoretical 73.563, difference 15.601
Sent  1,000,000,000 size:  192-Byte done!	Got  1,000,000,000 took  20.6400 sec, thr: 70.980 Gbps, theoretical 80.672, difference 9.693
Sent  1,000,000,000 size:  256-Byte done!	Got  1,000,000,000 took  25.7600 sec, thr: 76.532 Gbps, theoretical 84.768, difference 8.236
Sent  1,000,000,000 size:  320-Byte done!	Got  1,000,000,000 took  30.8800 sec, thr: 80.301 Gbps, theoretical 87.432, difference 7.131
Sent  1,000,000,000 size:  384-Byte done!	Got  1,000,000,000 took  36.0000 sec, thr: 83.027 Gbps, theoretical 89.302, difference 6.275
Sent  1,000,000,000 size:  448-Byte done!	Got  1,000,000,000 took  41.1200 sec, thr: 85.090 Gbps, theoretical 90.688, difference 5.598
Sent  1,000,000,000 size:  512-Byte done!	Got  1,000,000,000 took  46.2400 sec, thr: 86.706 Gbps, theoretical 91.756, difference 5.050
Sent  1,000,000,000 size:  576-Byte done!	Got  1,000,000,000 took  51.3600 sec, thr: 88.006 Gbps, theoretical 92.605, difference 4.598
Sent  1,000,000,000 size:  640-Byte done!	Got  1,000,000,000 took  56.4800 sec, thr: 89.074 Gbps, theoretical 93.294, difference 4.220
Sent  1,000,000,000 size:  704-Byte done!	Got  1,000,000,000 took  61.6000 sec, thr: 89.968 Gbps, theoretical 93.867, difference 3.899
Sent  1,000,000,000 size:  768-Byte done!	Got  1,000,000,000 took  66.7200 sec, thr: 90.727 Gbps, theoretical 94.349, difference 3.622
```
In the form of figure, it is like this: 
![image](https://user-images.githubusercontent.com/57842153/142599842-9ba17b57-705b-47e9-9542-cb9199000c64.png)
Do you have any idea about this situation?
Best.

**Comment by mariodruiz** [comment]
No idea. The numbers do not match up for some reason. It would be interesting to also show the bytes received in ol_w1_tg. For this you will have to modify the code in `vnx_util.py` to return it and then print it out.

What mode is the `ol_w1_tg` set to?

**Comment by IskandarZhang** [comment]
> No idea. The numbers do not match up for some reason. It would be interesting to also show the bytes received in ol_w1_tg. For this you will have to modify the code in `vnx_util.py` to return it and then print it out.
> 
> What mode is the `ol_w1_tg` set to?

Hi Mario, before I modified the code in `vnx_utils.py` I re-plug those two U50 and it seems works. The output is attached below and the `ol_w1_tg` is set to `CONSUMER`.
```
Sent      1,000,000 size:   64-Byte done!	Got      1,000,000 took   0.0104 sec, thr: 49.231 Gbps, theoretical 58.182, difference 8.951
Sent      1,000,000 size:  128-Byte done!	Got      1,000,000 took   0.0167 sec, thr: 61.440 Gbps, theoretical 73.563, difference 12.123
Sent      1,000,000 size:  192-Byte done!	Got      1,000,000 took   0.0206 sec, thr: 74.419 Gbps, theoretical 80.672, difference 6.254
Sent      1,000,000 size:  256-Byte done!	Got      1,000,000 took   0.0258 sec, thr: 79.503 Gbps, theoretical 84.768, difference 5.265
Sent      1,000,000 size:  320-Byte done!	Got      1,000,000 took   0.0309 sec, thr: 82.902 Gbps, theoretical 87.432, difference 4.530
Sent      1,000,000 size:  384-Byte done!	Got      1,000,000 took   0.0360 sec, thr: 85.333 Gbps, theoretical 89.302, difference 3.969
Sent      1,000,000 size:  448-Byte done!	Got      1,000,000 took   0.0411 sec, thr: 87.160 Gbps, theoretical 90.688, difference 3.529
Sent      1,000,000 size:  512-Byte done!	Got      1,000,000 took   0.0462 sec, thr: 88.581 Gbps, theoretical 91.756, difference 3.175
Sent      1,000,000 size:  576-Byte done!	Got      1,000,000 took   0.0514 sec, thr: 89.720 Gbps, theoretical 92.605, difference 2.885
Sent      1,000,000 size:  640-Byte done!	Got      1,000,000 took   0.0565 sec, thr: 90.652 Gbps, theoretical 93.294, difference 2.643
Sent      1,000,000 size:  704-Byte done!	Got      1,000,000 took   0.0616 sec, thr: 91.429 Gbps, theoretical 93.867, difference 2.438
Sent      1,000,000 size:  768-Byte done!	Got      1,000,000 took   0.0667 sec, thr: 92.086 Gbps, theoretical 94.349, difference 2.262
Sent      1,000,000 size:  832-Byte done!	Got      1,000,000 took   0.0718 sec, thr: 92.650 Gbps, theoretical 94.761, difference 2.110
Sent      1,000,000 size:  896-Byte done!	Got      1,000,000 took   0.0770 sec, thr: 93.139 Gbps, theoretical 95.117, difference 1.977
Sent      1,000,000 size:  960-Byte done!	Got      1,000,000 took   0.0821 sec, thr: 93.567 Gbps, theoretical 95.427, difference 1.860
Sent      1,000,000 size: 1024-Byte done!	Got      1,000,000 took   0.0872 sec, thr: 93.945 Gbps, theoretical 95.701, difference 1.756
Sent      1,000,000 size: 1088-Byte done!	Got      1,000,000 took   0.0923 sec, thr: 94.281 Gbps, theoretical 95.944, difference 1.663
Sent      1,000,000 size: 1152-Byte done!	Got      1,000,000 took   0.0974 sec, thr: 94.581 Gbps, theoretical 96.160, difference 1.579
Sent      1,000,000 size: 1216-Byte done!	Got      1,000,000 took   0.1026 sec, thr: 94.852 Gbps, theoretical 96.355, difference 1.503
Sent      1,000,000 size: 1280-Byte done!	Got      1,000,000 took   0.1077 sec, thr: 95.097 Gbps, theoretical 96.531, difference 1.434
Sent      1,000,000 size: 1344-Byte done!	Got      1,000,000 took   0.1128 sec, thr: 95.319 Gbps, theoretical 96.691, difference 1.371
Sent      1,000,000 size: 1408-Byte done!	Got      1,000,000 took   0.1179 sec, thr: 95.522 Gbps, theoretical 96.836, difference 1.314
Sent      1,000,000 size: 1472-Byte done!	Got      1,000,000 took   0.1230 sec, thr: 95.709 Gbps, theoretical 96.970, difference 1.261
Sent  1,000,000,000 size:   64-Byte done!	Got  1,000,000,000 took  10.4000 sec, thr: 49.231 Gbps, theoretical 58.182, difference 8.951
Sent  1,000,000,000 size:  128-Byte done!	Got  1,000,000,000 took  16.6667 sec, thr: 61.440 Gbps, theoretical 73.563, difference 12.123
Sent  1,000,000,000 size:  192-Byte done!	Got  1,000,000,000 took  20.6400 sec, thr: 74.419 Gbps, theoretical 80.672, difference 6.254
Sent  1,000,000,000 size:  256-Byte done!	Got  1,000,000,000 took  25.7600 sec, thr: 79.503 Gbps, theoretical 84.768, difference 5.265
Sent  1,000,000,000 size:  320-Byte done!	Got  1,000,000,000 took  30.8800 sec, thr: 82.902 Gbps, theoretical 87.432, difference 4.530
Sent  1,000,000,000 size:  384-Byte done!	Got  1,000,000,000 took  36.0000 sec, thr: 85.333 Gbps, theoretical 89.302, difference 3.969
Sent  1,000,000,000 size:  448-Byte done!	Got  1,000,000,000 took  41.1200 sec, thr: 87.160 Gbps, theoretical 90.688, difference 3.529
Sent  1,000,000,000 size:  512-Byte done!	Got  1,000,000,000 took  46.2400 sec, thr: 88.581 Gbps, theoretical 91.756, difference 3.175
Sent  1,000,000,000 size:  576-Byte done!	Got  1,000,000,000 took  51.3600 sec, thr: 89.720 Gbps, theoretical 92.605, difference 2.885
Sent  1,000,000,000 size:  640-Byte done!	Got  1,000,000,000 took  56.4800 sec, thr: 90.652 Gbps, theoretical 93.294, difference 2.643
Sent  1,000,000,000 size:  704-Byte done!	Got  1,000,000,000 took  61.6000 sec, thr: 91.429 Gbps, theoretical 93.867, difference 2.438
Sent  1,000,000,000 size:  768-Byte done!	Got  1,000,000,000 took  66.7200 sec, thr: 92.086 Gbps, theoretical 94.349, difference 2.263
Sent  1,000,000,000 size:  832-Byte done!	Got  1,000,000,000 took  71.8400 sec, thr: 92.650 Gbps, theoretical 94.761, difference 2.110
Sent  1,000,000,000 size:  896-Byte done!	Got  1,000,000,000 took  76.9600 sec, thr: 93.139 Gbps, theoretical 95.117, difference 1.977
Sent  1,000,000,000 size:  960-Byte done!	Got  1,000,000,000 took  82.0800 sec, thr: 93.567 Gbps, theoretical 95.427, difference 1.860
Sent  1,000,000,000 size: 1024-Byte done!	Got  1,000,000,000 took  87.2000 sec, thr: 93.945 Gbps, theoretical 95.701, difference 1.756
Sent  1,000,000,000 size: 1088-Byte done!	Got  1,000,000,000 took  92.3200 sec, thr: 94.281 Gbps, theoretical 95.944, difference 1.663
Sent  1,000,000,000 size: 1152-Byte done!	Got  1,000,000,000 took  97.4400 sec, thr: 94.581 Gbps, theoretical 96.160, difference 1.579
Sent  1,000,000,000 size: 1216-Byte done!	Got  1,000,000,000 took 102.5600 sec, thr: 94.852 Gbps, theoretical 96.355, difference 1.503
Sent  1,000,000,000 size: 1280-Byte done!	Got  1,000,000,000 took 107.6800 sec, thr: 95.097 Gbps, theoretical 96.531, difference 1.434
Sent  1,000,000,000 size: 1344-Byte done!	Got  1,000,000,000 took 112.8000 sec, thr: 95.319 Gbps, theoretical 96.691, difference 1.371
Sent  1,000,000,000 size: 1408-Byte done!	Got  1,000,000,000 took 117.9200 sec, thr: 95.522 Gbps, theoretical 96.836, difference 1.314
Sent  1,000,000,000 size: 1472-Byte done!	Got  1,000,000,000 took 123.0400 sec, thr: 95.709 Gbps, theoretical 96.970, difference 1.261
```
Moreover, I noticed that there is still a certain gap between the theoretical and the actual thr value. Is this gap acceptable? How can I improve to close the gap? 
Best.

**Comment by mariodruiz** [comment]
The difference is acceptable. To get closer to the theoretical value, you will have to re design the Network layer from scratch.

**Comment by mariodruiz** [comment]
@IskandarZhang if the issue is resolved. Can you please close it?

**Comment by IskandarZhang** [comment]
> @IskandarZhang if the issue is resolved. Can you please close it?

Hi Mario, sorry about forgot to close this issue and thanks again.
